# app.config.yml.default
# Copy to app.config.yml
production:
  app:
    log-path: /var/log/channel_poller.log

test:
  app:
    log-path: /var/log/channel_poller.log

development:
  app:
    log-path: /var/log/channel_poller.log
